from datetime import datetime
from typing import Any, Dict, List, Optional
from sqlalchemy.ext.asyncio import AsyncSession
from backend.app.models.automation import AutomationWorkflow, WorkflowCondition, WorkflowAction, WorkflowExecutionLog
from backend.app.repositories.automation import WorkflowRepository, ExecutionLogRepository
from backend.app.services.base import BaseService
from backend.app.schemas.automation import WorkflowCreate, WorkflowTriggerRequest

class AutomationEngine:
    @staticmethod
    def evaluate_condition(payload: Dict[str, Any], condition: WorkflowCondition) -> bool:
        val = payload.get(condition.field_path)
        if val is None:
            return False

        op = condition.operator.lower()
        target = condition.target_value

        try:
            if op in ["gt", "gte", "lt", "lte"] and isinstance(val, (int, float)):
                t_num = float(target)
                if op == "gt": return val > t_num
                if op == "gte": return val >= t_num
                if op == "lt": return val < t_num
                if op == "lte": return val <= t_num
            elif op == "eq":
                return str(val).lower() == target.lower()
            elif op == "neq":
                return str(val).lower() != target.lower()
            elif op == "contains":
                return target.lower() in str(val).lower()
        except Exception:
            return False
        return False

class WorkflowService(BaseService[AutomationWorkflow, WorkflowRepository]):
    def __init__(self, db: AsyncSession):
        super().__init__(WorkflowRepository(db))
        self.log_repo = ExecutionLogRepository(db)

    async def create_workflow(self, req: WorkflowCreate, tenant_id: str) -> AutomationWorkflow:
        wf = await self.repository.create({
            "name": req.name,
            "description": req.description,
            "is_active": True,
            "trigger_event": req.trigger_event,
            "trigger_config": req.trigger_config or {}
        }, tenant_id=tenant_id)

        for cond in req.conditions:
            c = WorkflowCondition(
                workflow_id=wf.id,
                field_path=cond.field_path,
                operator=cond.operator,
                target_value=cond.target_value
            )
            self.repository.db.add(c)

        for act in req.actions:
            a = WorkflowAction(
                workflow_id=wf.id,
                action_type=act.action_type,
                action_config=act.action_config,
                execution_order=act.execution_order or 1
            )
            self.repository.db.add(a)

        await self.repository.db.flush()
        return await self.repository.get_with_rules(wf.id, tenant_id)

    async def execute_trigger(self, req: WorkflowTriggerRequest, tenant_id: str) -> List[WorkflowExecutionLog]:
        workflows = await self.repository.list_active_by_trigger(req.event_name, tenant_id)
        logs = []

        for wf in workflows:
            # Check all conditions (AND logic)
            all_passed = True
            for cond in wf.conditions:
                if not AutomationEngine.evaluate_condition(req.payload, cond):
                    all_passed = False
                    break

            if not all_passed:
                log = await self.log_repo.create({
                    "workflow_id": wf.id,
                    "entity_type": req.entity_type,
                    "entity_id": req.entity_id,
                    "status": "skipped",
                    "payload_snapshot": req.payload
                }, tenant_id=tenant_id)
                logs.append(log)
                continue

            # Execute actions
            try:
                for action in wf.actions:
                    # Execute action based on action_type
                    if action.action_type == "create_task":
                        from backend.app.models.task import Task
                        task = Task(
                            tenant_id=tenant_id,
                            title=action.action_config.get("title", f"Automation Task for {req.entity_type}"),
                            description=action.action_config.get("description", "Generated by Automation Engine"),
                            priority=action.action_config.get("priority", "high"),
                            entity_type=req.entity_type,
                            entity_id=req.entity_id
                        )
                        self.repository.db.add(task)
                    elif action.action_type == "send_email":
                        from backend.app.models.communication import CommunicationMessage
                        msg = CommunicationMessage(
                            tenant_id=tenant_id,
                            channel="email",
                            sender="automation@clientflow.internal",
                            recipient=action.action_config.get("recipient", "manager@clientflow.internal"),
                            subject=action.action_config.get("subject", "Automation Alert"),
                            body_text=action.action_config.get("body", f"Event {req.event_name} triggered on {req.entity_type}"),
                            status="sent",
                            entity_type=req.entity_type,
                            entity_id=req.entity_id
                        )
                        self.repository.db.add(msg)

                await self.repository.db.flush()
                log = await self.log_repo.create({
                    "workflow_id": wf.id,
                    "entity_type": req.entity_type,
                    "entity_id": req.entity_id,
                    "status": "success",
                    "payload_snapshot": req.payload
                }, tenant_id=tenant_id)
                logs.append(log)
            except Exception as e:
                log = await self.log_repo.create({
                    "workflow_id": wf.id,
                    "entity_type": req.entity_type,
                    "entity_id": req.entity_id,
                    "status": "failed",
                    "error_message": str(e),
                    "payload_snapshot": req.payload
                }, tenant_id=tenant_id)
                logs.append(log)

        return logs
